### ISSUE TITLE
Custom Components reference on Stateful-Components page - what does it refer to?

### ISSUE THREAD

**Issue by phollyer** [adospace/reactorui-maui-docs#2]
On the Stateful-Components  page, line 65 says:

"NOTE: Do not use constructors to pass parameters to the component, but public properties instead (take a look at the Custom Components documentation page)."

I was going to add a link to the Custom Components page, but don't know which page it should link to as there is no Custom Components page.

**Comment by adospace** [comment]
I've added the Component Properties page where is described how to set properties on components and linked this note to it.
Thanks
